# Generated by Django 5.2 on 2025-04-30 02:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='پایه تحصیلی')),
                ('order', models.IntegerField(verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پایه تحصیلی',
                'verbose_name_plural': 'پایه\u200cهای تحصیلی',
                'ordering': ['school', 'order'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مدرسه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'مدرسه',
                'verbose_name_plural': 'مدارس',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام کلاس')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانش\u200cآموزان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to=settings.AUTH_USER_MODEL, verbose_name='دانش\u200cآموزان')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='scores.grade', verbose_name='پایه تحصیلی')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['grade', 'name'],
                'unique_together': {('grade', 'name')},
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='scores.school', verbose_name='مدرسه'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام درس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='scores.grade', verbose_name='پایه تحصیلی')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['grade', 'name'],
                'unique_together': {('grade', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.class', verbose_name='کلاس')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.userprofile', verbose_name='دانش\u200cآموز')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scores.subject', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'نمره دانش\u200cآموز',
                'verbose_name_plural': 'نمرات دانش\u200cآموزان',
                'db_table': 'gym_studentscore',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('school', 'name')},
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='نمره')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scores.class', verbose_name='کلاس')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='gym.userprofile', verbose_name='دانش\u200cآموز')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scores.subject', verbose_name='درس')),
            ],
            options={
                'verbose_name': 'نمره',
                'verbose_name_plural': 'نمرات',
                'ordering': ['-date', 'user_profile'],
                'unique_together': {('user_profile', 'subject', 'date')},
            },
        ),
    ]
