# Generated by Django 5.0.2 on 2025-05-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_card_number', models.CharField(help_text='شماره کارت که به کاربران نمایش داده می\u200cشود', max_length=16, verbose_name='شماره کارت پرداخت')),
                ('payment_card_owner', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام صاحب کارت')),
                ('payment_description', models.TextField(blank=True, help_text='توضیحات پرداخت که به کاربران نمایش داده می\u200cشود', null=True, verbose_name='توضیحات پرداخت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
