# Generated by Django 5.0.2 on 2025-05-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examregistration',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='شماره کارت'),
        ),
    ]
