# Generated by Django 5.0.2 on 2025-05-12 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_examregistration_card_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات سایت', 'verbose_name_plural': 'تنظیمات سایت'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='payment_card_number',
            field=models.CharField(help_text='شماره کارت که به کاربران نمایش داده می\u200cشود (بدون فاصله وارد کنید: مثلا 6104338968423552)', max_length=16, verbose_name='شماره کارت پرداخت'),
        ),
    ]
