# Generated by Django 5.0.2 on 2025-05-12 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'تنظیمات پرداخت', 'verbose_name_plural': 'تنظیمات پرداخت'},
        ),
    ]
