# Generated by Django 5.2 on 2025-05-06 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_add_completed_status'),
        ('gym', '0004_alter_planrequest_status'),
    ]

    operations = [
    ]
