# Generated by Django 5.0.2 on 2025-05-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='agreement_accepted',
            field=models.BooleanField(default=False, verbose_name='توافقنامه پذیرفته شده'),
        ),
    ]
