# Generated by Django 5.0.2 on 2025-05-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_bookletpayment_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('verification_code', models.CharField(max_length=10, verbose_name='کد تایید')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('attempts', models.IntegerField(default=0, verbose_name='تعداد تلاش')),
                ('max_attempts', models.IntegerField(default=3, verbose_name='حداکثر تعداد تلاش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
            ],
            options={
                'verbose_name': 'تایید شماره موبایل',
                'verbose_name_plural': 'تایید شماره\u200cهای موبایل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='شماره تلفن تایید شده'),
        ),
    ]
