# Generated by Django 5.0.2 on 2025-05-12 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_phoneverification_userprofile_phone_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
        migrations.RemoveField(
            model_name='bookletpayment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_verified',
        ),
    ]
